### ISSUE TITLE
训练文件

### ISSUE THREAD

**Issue by world2025** [TreezzZ/DHN_PyTorch#1]
您好！非常感谢您的开源，请问您可以分享一下nus_wide的train_img.txt和train_label_onehot_tc21.txt吗？谢谢！

**Comment by TreezzZ** [comment]
> 您好！非常感谢您的开源，请问您可以分享一下nus_wide的train_img.txt和train_label_onehot_tc21.txt吗？谢谢！

README里的下载地址包括全部数据集文件。

这个是单独的train文件txt，解压放到nus-wide数据集里，链接: https://pan.baidu.com/s/1nx3K2E9b3lIyWrm-cRmjVQ 提取码: d67s

**Comment by world2025** [comment]
我根据您其他的模型给改好了😷，主要是百度云限速，不想重新下数据集了，太大了😹------------------ 原始邮件 ------------------
发件人: "Tree"<notifications@github.com>
发送时间: 2020年1月8日(星期三) 晚上10:30
收件人: "TreezzZ/DHN_PyTorch"<DHN_PyTorch@noreply.github.com>;
抄送: "tkone2018"<843783062@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [TreezzZ/DHN_PyTorch] 训练文件 (#1)


 
您好！非常感谢您的开源，请问您可以分享一下nus_wide的train_img.txt和train_label_onehot_tc21.txt吗？谢谢！
  
README里的下载地址包括全部数据集文&#x4EF6;。
 
这个是单独的train文&#x4EF6;txt，解压放到nus-wide数据集里，链接: https://pan.baidu.com/s/1nx3K2E9b3lIyWrm-cRmjVQ 提取码: d67s
 
&mdash;
